Fall-out characters from API Key included. Observarions: =============
-I am finding that [17] – appending 100 JSON records from csv file - all 20K size, 1 JSON 2k - to trump_tweets – took longer than I expected  (30 sec);
I believe it is b/c every JSON metadata-file is stored as a separate text -varchar field in my sql db?
- [14] is 9 ms-word docs, to which much smaller meta-data JSON is added (33bytes) – and this was pretty fast. (10x less docs, and ~100x less size of JSON meta-data than in tweets [17] example.
- [23] topics API is tested on tweets only, which are relatively small text files;
I hope there will be examples to test with doc, docx, and pdf files – which are binary files, and much larger in size than individual tweets.
-[27, 28, 29, 30] topic summary, topic sentiment, topic consensus work well on the set of 7 tweets
- [30] topic historical analysis fails due to Recursion Error either b/c of the stack overflow, or too many jobs spawned (# noqa: E501)
- [32] Get author connectivity for tweets dataset fails
----------------- Get author connectivity for trump_tweets -----
ERROR: {'stack': 'Traceback (most recent call last):\ etc ----------------------------------------------------------------------
-[37] Topic transfer is fast on tweets text files; hope I’ll see examples with pdfs,  and docs, and get feeling about the processing time.
- [38] I will need to look-up the dictionary for a transfer of “exogenously exposed topics”, it work fast on tweets text files.
- [39] Topics sentiment transfer is fast on text files
- [40] Topics consensus transfer is fast on 7 text files. The same for [41] topic delta.
- [42] Get doc metadata only (info w/out content) is fast for 10 tweets.
- [43] Get doc metadata for selected doc is ok
- [44] Get doc details (content + metadata) is fast, especially when doc does not have content
- [45] *** Get Document Recommendations is especially important for PTS
This particular example is recommending tweets, and ranking tweets based on proposed topic.
I’d like to see this example with pdf, and doc, docx documents of medical content, and proper grouping and ranking.
- [46] Get document summary – looks as a good feature for PTS, too. Extracting the main content from the document.
- [47] Get document sentiment – on the scale from negative – zero(neutral) – positive
- [48] ***Tagging documents feature can be useful for PTS – document with the same tag can be grouped
- [49] Summary of a remote document in pdf format – provided on remote location with URL  - this could be useful for PTS, too.